// Generated by https://quicktype.io

export interface ProductType {
  id: string;
  imagen: string;
  nombre: string;
  orden: number;
  descripcion: string;
  categoria: Categoria;
  disponible: Disponible;
  estado: boolean;
  precio: number;
  impuesto: Impuesto[];
}

export interface Categoria {
  descripcion: string;
  salsas?: boolean;
  id: string;
  nombre: string;
}

export interface Impuesto {
  descripcion: string;
  id: string;
  nombre: string;
  porcentaje?: number;
}

export interface Disponible {
  app: boolean;
  domicilio: boolean;
  caja: boolean;
}
